### PR TITLE
BUG: Handle Negative Timer

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes: #150 Handle the negative value in timer now if we enter negative value then it mapped to 0 immediately!

**NOW:**

https://github.com/user-attachments/assets/8d59a01a-5556-4e0a-9e70-5e9d047b317c

@param-code Please review my PR and merge accordingly!

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@param-code Please review my PR:)

**Comment by harshbhar0629** [comment]
??

**Comment by harshbhar0629** [comment]
@param-code Please review my PR.

**Comment by param-code** [comment]
> Fixes: #150 Handle the negative value in timer now if we enter negative value then it mapped to 0 immediately!
> 
> **NOW:**
> 
>  setTimer.mp4 
> @param-code Please review my PR and merge accordingly!

this issue has already been resolved.

**Comment by harshbhar0629** [comment]
But this issue assigned to me?

**Comment by param-code** [comment]
> But this issue assigned to me?

This issue is resolved by someone who was assigned earlier.

**Comment by harshbhar0629** [comment]
Ok!

**Pull request closed without merging**
