### PR TITLE
added validation

### PR DESCRIPTION
**Pull request by Gauravtb2253**
I have added input validation to login and signup page
Pls check

### CODE REVIEW

**Comment by param-code** [comment]
Great Work @Gauravtb2253 .

**Comment by Gauravtb2253** [comment]
do you have any specific issue for me to solve

**Comment by param-code** [comment]
> do you have any specific issue for me to solve

you may try to add chat feature #142.

**Comment by Gauravtb2253** [comment]
do you have any other issue
I am not much aware of socket programming

**Pull request merged**
