### PR TITLE
Create footer.css

### PR DESCRIPTION
**Pull request by ark0078**
I've fixed the spacing as well as inappropriate alignment of "Home","timer" and "World Clock" and the copyright portion too

### CODE REVIEW

**Comment by ark0078** [comment]
Screenshot (191)
@param-code

**Comment by param-code** [comment]
Sure.

**Comment by ark0078** [comment]
Hey,can we get connected over email? @param-code

**Comment by param-code** [comment]
Yeah sure.

**Comment by ark0078** [comment]
May I have your email please?I want to inform you about something exciting.. @param-code

**Comment by param-code** [comment]
> May I have your email please?I want to inform you about something exciting.. @param-code

[Here](mailto:sparamveer1001@gmail.com)

**Comment by param-code** [comment]
> > May I have your email please?I want to inform you about something exciting.. @param-code
> 
>  [Here](mailto:sparamveer1001@gmail.com)

**Pull request merged**
