### PR TITLE
Bug-Fix: Fixing Position of Footer across pages

### LINKED ISSUE #62: Maintain Uniformity while Navigating
Footer position can be fix while navigating to different sections 
- Counter 
- Timer
- World Clock

### PR DESCRIPTION
**Pull request by ArinNigam**
Works as expected and fix #62

https://github.com/user-attachments/assets/1070d5bd-47bd-48d3-8211-83d0ddc7395a

### CODE REVIEW

**Comment by param-code** [comment]
Great.Thanks for contributing and Congratulation!!

**Comment by param-code** [comment]
> Works as expected and fix #62
> 
>  Fix.footer.postion.mov

Well its not working as shown in the video

**Comment by ArinNigam** [comment]
@param-code are you running it locally ?

**Comment by param-code** [comment]
> @param-code are you running it locally? Because i can't preview production on vercel it requires access.
> For me it's working fine on my local machine.

no but in production. you can send the request I will provide the access

**Comment by ArinNigam** [comment]
@param-code I think the deployment is failing due to some underlying issue which have been mentioned by people in #50
Check from your side on vercel why is it so?
It isn't related to my PR.

**Comment by param-code** [comment]
All  the Best!!

**Pull request merged**
