### PR TITLE
Add Visitor Count Feature ✨ 

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
Fix Issue - #333 

image
image
image

### CODE REVIEW

**Comment by AnushkaChouhan25** [comment]
@param-code Please assign this issue under level 3

**Comment by param-code** [comment]
> @param-code Please assign this issue under level 3, other projects level image
> 
> Thank you :)

At most i can provide you level 2 for this.

**Comment by AnushkaChouhan25** [comment]
@param-code Ok

**Comment by AnushkaChouhan25** [comment]
@param-code Please assign with labels

**Pull request merged**
