### PR TITLE
google multilanguage integrated

### PR DESCRIPTION
**Pull request by 17arindam**
-added a interface to select a language you want to view website in the footer
-the website will be changed to selected language

https://github.com/user-attachments/assets/1f4b6602-2ada-468f-abef-fb387eafe46c

### CODE REVIEW

**Comment by 17arindam** [comment]
@param-code please review my pr issue no #102

**Comment by param-code** [comment]
> @param-code please review my pr issue no #102

You have done a great job @17arindam.Thanks for contributing.

**Comment by 17arindam** [comment]
@param-code you have assigned me level 2 for this issue and here you have assigned me level 1 in pr

**Comment by 17arindam** [comment]
@param-code please review my issue no #102

**Pull request merged**
