### PR TITLE
Enhance Stopwatch with Lap Time Analysis and Visualization Features

### PR DESCRIPTION
**Pull request by Lonwwolf14**
## Overview
This pull request introduces enhanced lap time analysis and visualization features to the existing stopwatch functionality. The improvements aim to provide users with deeper insights into their performance during timed activities.

### Lap Analysis
- **Average Lap Time:** Calculates and displays the average time taken for all laps.
- **Fastest Lap:** Identifies and displays the lap with the fastest time.
- **Slowest Lap:** Identifies and displays the lap with the slowest time.

### Visualization
- **Bar Chart:** Implements a bar chart to visually display each lap's time.

## Video Demonstration
A video demonstration showcasing the new features has been included for reference. 

https://github.com/user-attachments/assets/b5435313-837c-46d6-a34a-8628d7187667

### CODE REVIEW

**Comment by Lonwwolf14** [comment]
Lemme know if any further updates are required !!

**Comment by Lonwwolf14** [comment]
My i know what the problem is?

**Comment by param-code** [comment]
> My i know what the problem is?

image
its showing this :(

**Comment by param-code** [comment]
Congratulations!! You have done a great Job!!

**Pull request merged**
