### PR TITLE
Add responsive world clock feature with country selection

### PR DESCRIPTION
**Pull request by 17arindam**
-Created a new world clock page.
-Implemented country selection with dynamic time zone support.
-Integrated an analog clock to display time.
-Added date functionality to show the current date for the selected location.
-Ensured the page is fully responsive for mobile, tablet, and desktop users.
Screenshot 2024-10-02 134706

### CODE REVIEW

**Comment by 17arindam** [comment]
@param-code hey i have created the world clock but i cant understand the deployment error can you send me the details of the error

**Comment by param-code** [comment]
> @param-code hey i have created the world clock but i cant understand the deployment error can you send me the details of the error

image
there is some issue with your worldclock file ig

**Comment by param-code** [comment]
> > @param-code hey i have created the world clock but i cant understand the deployment error can you send me the details of the error
> 
> image there is some issue with your worldclock file ig

I have found your error
image
here your name of file is not Matching :(

**Comment by param-code** [comment]
Great Work Man!! But how we are gonna navigate through stopwatch timer and world clock,if you would like to work on that too,feel free to create an issue.

**Comment by 17arindam** [comment]
hey @param-code  just asking you have assigned me this task for level 3 but you have given me level 2 it would be great if you can assign it level 3 . please check issue no #8 . so if possible it would be a great help and yeah i would like to work on that navigation issue too

**Pull request merged**
