### PR TITLE
Todo

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello
I have added the code for adding todo and displaying it
The user can also delete it

image

### CODE REVIEW

**Comment by param-code** [comment]
Good Job @Gauravtb2253 but you forgot to add the access part.How the user will be able to access it??

**Comment by Gauravtb2253** [comment]
Also do you have more issues to solve
I can do it

**Comment by param-code** [comment]
> Also do you have more issues to solve I can do it

#142  #141 or feel free to add some other feature or whatever you think would be good.

**Comment by param-code** [comment]
> > Good Job @Gauravtb2253 but you forgot to add the access part.How the user will be able to access it??
> 
> I didnt get the access part Can you pls explain

You haven't added any button in the frontend for the route you the added in the backend.How someone will access it??

**Comment by Gauravtb2253** [comment]
> > > Good Job @Gauravtb2253 but you forgot to add the access part.How the user will be able to access it??
> > 
> > 
> > I didnt get the access part Can you pls explain
> 
> You haven't added any button in the frontend for the route you the added in the backend.How someone will access it??

When the user is logged in there is a plus sign shown in the navbar
From there user can see all todos and add or delete them

**Pull request merged**
