### PR TITLE
Added Spotify player

### PR DESCRIPTION
**Pull request by Saaarthak0102**
### 📥 Pull Request

Fixes Issue #140

## Description

Added Spotify Music Player: Introduced a sliding music player embedded with Spotify to enhance the user experience during study sessions.

## Features added

a) Spotify Music Player Integration: Implemented a Spotify player that can be controlled globally, allowing users to enjoy music without interruptions while navigating the site.

b) Sliding Animation: The player smoothly slides in from the right when hovering over the Spotify icon, improving accessibility and user interaction.

image

## Reason for Change

The integration of the Spotify player provides users with an engaging experience while studying or working on the site. The sliding feature enhances usability by keeping the interface clean and intuitive.

## Types of Changes

Enhancement (non-breaking change that improves the functionality and user experience)

## Checklist

 My code follows the style guidelines of this project
 I have performed a self-review of my code
 I have commented my code, particularly in hard-to-understand areas
 New and existing unit tests pass locally with my changes
 Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Saaarthak0102 — COMMENTED** [review]
reviewed

**Comment by Saaarthak0102** [comment]
Although I took help from gpt to work on this feature as I dont have that much skills, thank you for assigning this!

**Review by Saaarthak0102 — COMMENTED** [review]
reviewed

**Comment by param-code** [comment]
Kinda Nice one @Saaarthak0102 .

**Comment by Saaarthak0102** [comment]
> Kinda Nice one @Saaarthak0102 .

Thanks 👍

**Pull request merged**
