### PR TITLE
added  google /apple login & change the ui of signup/login page 

### PR DESCRIPTION
**Pull request by REHAN-18**
updated the sign-up/login page with google/apple login with modern signup/login page..
**issue #246** 

now----
Screenshot 2024-10-23 at 9 36 26 PM
Screenshot 2024-10-23 at 9 36 32 PM

before---
Screenshot 2024-10-23 at 9 28 56 PM
before

### CODE REVIEW

**Comment by REHAN-18** [comment]
@param-code bro merge this asap  !!!

**Comment by REHAN-18** [comment]
@param-code if possible give level 3 label !!!

**Comment by REHAN-18** [comment]
@@param-code bro pls see the pr!!

**Comment by param-code** [comment]
> @@param-code bro pls see the pr!!

Yes yes @REHAN-18 .

**Pull request merged**
