### PR TITLE
✨added local storage✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
added a local storage to save the user input in the local storage and redirects to home page.

https://github.com/user-attachments/assets/c881b7b1-47db-46ed-93ad-d751e5b321ff

@param-code can you please review this code, thank you!

### CODE REVIEW

**Comment by param-code** [comment]
> added a local storage to save the user input in the local storage and redirects to home page.
> 
>  Screen.Recording.2024-10-12.at.10.01.51.PM.1.mp4 
> @param-code can you please review this code, thank you!

Sure.

**Comment by param-code** [comment]
Congratulations!! and thanks for your contribution.

**Comment by T-Rahul-prabhu-38** [comment]
bhaiya isnt storage code level2.

**Comment by param-code** [comment]
> @param-code bhaiya isnt storage code level2. u have signed level2 in the issue.

Sorry @T-Rahul-prabhu-38 .I have changed the tag now.

**Comment by T-Rahul-prabhu-38** [comment]
thank you.

**Pull request merged**
